import { Inter } from "next/font/google";
import "@/css/globals.css";
import Providers from "@/ReactQuery/Provider";
import Footer from "@/components/Common/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TLN",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
